# SVM

In order to understand demand in different areas of the city better, we used two prediction models: neural network and SVM.
Specifically, in this section we will be focusing on SVM with regression, in other words SVR.
The objective of the model is to predict the trip demand particularly the trip count as accurately as possible.

Our SVR model is trained and tested on the data as described above.
----

The models were trained using a combination of three different spatial units: These are hexagons [@h3_github], census tracts [@census_data], and community areas [@community_area_data].
The chosen time frames are one hour, four hours, and twenty-four hours. 
Our target and opjective is trip count. 
Our features include: Cyclic encoded time, including hour, weekday, and month.
We also include weather data [@iem_asos_mdw_2024_2026], whether the day is a holiday, and points of interest in the city. 
Since we have three different spatial units, the spatial encoding had to work for all three units.
Different encodings were taken into consideration such as spatial embedding, onehot encoding and latitude longitude encoding.
As a result of working with all three spatial units, longitude-latitude encoding was chosen. 
Due to the dependencies between latitude and longitude, spherical encoding was performed on them.


Since the dataset contains a significant amount of data, reducing the runtime was an important step.
We started out with a simple kernel which grew into a pipeline.
At one point we had to place the focus of the pipeline on runtime reduction.
However, once this was resolved, enhancing the SVM's performance became the primary concern.
We developed a pipeline for SVR with models from scikit-learn[]. The SVR/LinearSVR model was changed to the equilifiant model form cuml[@cuml]. 
Due to this still not working perfectly the model was trained on the GPU with cuml[@cuml].
During this we found a bug in cuml which left us unable to train the model on the whole dataset. 
Further information can be found in the appendix. 


## Results

{{< embed notebooks/03_04_predictive_analytics_svm_comparison.ipynb#compare_to_baseline>}}
{{< embed notebooks/03_04_predictive_analytics_svm_comparison.ipynb#heat_map_svm>}}

We compared the svr model to three baseline model.
These baseline model either use zero, global median or the mean of the time and spatial unit.
Our model performs better than the global median and zero model. But it performs worse than the mean of spatial and time unit model.
This could have multiple reasons. But the most likely reason might be the dataset consisting mostly of zeroes.
In SVMs this might lead to... which are things we also observed.

The SVR's best performance compared to the baseline is for spatial unit hexagon 7 and the four-hour time frame.
The differences from the baseline model are small, though, apart from the metrics for the 24-hour time frame.

When comparing different time frames and spatial units, Hexagon with a resolution of 8 seems to perform the best, except for the R2 metric.


### How spatial resolution seems to change the outcome?

Both hexagons seem to perform best. The sparser grid of 7 seems to perform better with the R² score, whereas the Hexagon grid with a resolution of 8 performs better with the mean absolute error. Census tracts perform the worst in the R² metric, whereas community areas perform the worst in the mean absolute error and root mean squared error metrics.
Both of these seem to perform mediocre for the other metrics.

### How temporal resoltion changed the outcome?

Overall, a smaller temporal resolution tends to be better, while a larger one tends to be worse.
The performance of the community areas is especially poor for the twenty-four hour dataset.


## SVC
The classification was developed at the side and run on all the spatial units, but only with time frame 4.
T
SVC also has a problem with the zero infalted dataset. Here the zeroes are purposfully excluded while determining the classes and get their own class.
here the decision can be made whether 

## Results

## Recommendation
If SVMs are desired, the time frame should be short and the spatial unit should be hexagons.

## Further Improvement

In case, we want to keep using SVMs. We would try 




The next time we would find us with a big dataset, instead of finding the first thing should be to fit the model in a reasonable time.
Once this is established the model fitting can be achieved.
We need to either change the way the data preparation is done and potentially exclude spatial units outside the city which are shown to have a lot of zeroes.
Or change to a model which can better handle an excess of zeroes. One of such models would be the ZeroInflatedPoisson[@quelle]-
The first improvement we would recommend it to use data, that does not consist of a lot of trip count zero.
This lead to bad convergance during the grid search as well as the model fitting.
The next time we would also recommend to directly develop the model to run on GPU due to the significant amount of data.
But overall we would not recommend to use SVMs for this kind of data especially for classification there are models which can handle more similar data better.






 