# Appendix SVM

## Bug found in cuml
Cuml appears to encounter challenges when confronted with substantial data sets, resulting in negative R2 values and a progressive decline in performance over time.

## Steps in developing SVM

These are the changes we made during the developement of the svm in steps and why we decided on them:
- We started with a basic svr on an rbf kernel which is the basic kernel for scikits[@sklearn_api; @pedregosa2011scikit] implementation of svms.
- Then we added grid search to find good hyperparameter.
- SVM work better on scaled data, therefore we added a StandardScaler[@sklearn_api; @pedregosa2011scikit].
- Since we were running into runtime issues we changed changed grid search to only include the hyperparameter relevant for each kernel.
- To further counteract these issues we added Nystroem[@sklearn_api; @pedregosa2011scikit].
- Due to the same reason, we changed GridSearchCV[@sklearn_api; @pedregosa2011scikit] to RandomSearchCV.
- Since we were using a pipeline now we also added the StandardScaler to the Pipeline[].
- Since we were still runnig into issues withe the runtime and to get a better performing SVR we added TransformedTargetRegressor[@sklearn_api; @pedregosa2011scikit].
- For the same reason as before we added cashing(memory) to the pipeline.
- The SVM with the kernel linear was changed to LinearSVM[@sklearn_api; @pedregosa2011scikit].
- Use cuml[@rapids_cuml] to run model on the GPU instead of the CPU.
- Find a good subset of hyperparameter through testing.
- Changed from RandomSearchCV to HalvingGridSearchCV. Used  RandomSearchCV before since HalvingGridSearchCV is still experimental. For our data HalvingGridSearchCV seems to work better[@sklearn_api; @pedregosa2011scikit].


## Pipeline SVR/SVC
-
